Repository AdaCore/learn, pull requests merged in 2020-09, with the labels that each got.

#406 Fixing publish Makefile target to include copy of pdf_books to target.
  frontend/Makefile
Labels: bug

#386 Adding section on overlays for serialization
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/04_Embedded.rst
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/06_Translation.rst
Labels: new section

#421 Updating path to GNAT CE 2020 installer
  .travis.yml
Labels: small

#420 Adding section on pointer to subprograms
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/07_Reusability.rst
Labels: new section

#422 Minor corrections
  content/courses/GNAT_Toolchain_Intro/chapters/gnat_tools.rst
Labels: small

#424 Ace gutter annotations
  frontend/package.json
  frontend/src/ts/areas.ts
  frontend/src/ts/editor.ts
  frontend/src/ts/widget.ts
  frontend/tests/ts/areas.spec.ts
Labels: enhancement
