Repository AdaCore/learn, pull requests merged in 2020-12, with the labels that each got.

#456 Editorial changes to first page
  content/courses/Ada_For_The_C_Embedded_Developer/conf.txt
  content/courses/Ada_For_The_C_Embedded_Developer/index.rst
Labels: small

#436 Adding section on fixed-point types
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/04_Embedded.rst
Labels: new section

#432 Adding section on checks and assertions
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/02_Perspective.rst
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/05_SPARK.rst
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/08_Performance.rst
Labels: new section

#460 Fixed grammatical error in gprbuild.rst
  content/courses/GNAT_Toolchain_Intro/chapters/gprbuild.rst
Labels: typo

#459 fixed typo in standard library containers.rst
  content/courses/intro-to-ada/chapters/standard_library_containers.rst
Labels: typo

#458 Fixed typo in object_oriented_programming.rst
  content/courses/intro-to-ada/chapters/object_oriented_programming.rst
Labels: typo

#461 Fixed grammatical error in gnat_tools.rst
  content/courses/GNAT_Toolchain_Intro/chapters/gnat_tools.rst
Labels: typo

#462 Correcting language for code example.
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/02_Perspective.rst
Labels: small

#463 Editorial change: changing order of list of authors.
  content/courses/Ada_For_The_C_Embedded_Developer/conf.txt
  content/courses/Ada_For_The_C_Embedded_Developer/index.rst
Labels: small

#447 Adding section on interfacing with devices
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/04_Embedded.rst
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/06_Translation.rst
Labels: new section

#469 Editorial change: using LaTeX markup for separating authors.
  content/courses/Ada_For_The_C_Embedded_Developer/conf.txt
  content/courses/intro-to-ada/conf.txt
  content/courses/intro-to-spark/conf.txt
Labels: small

#474 Adding list of reviewers.
  content/courses/Ada_For_The_C_Embedded_Developer/index.rst
Labels: small

#476 Adding conclusion chapter
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/10_Conclusion.rst
Labels: new section

#478 Editorial change: correcting typo.
  content/courses/Ada_For_The_C_Embedded_Developer/index.rst
Labels: small

#479 Editorial changes: adding buttons to examples
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/04_Embedded.rst
Labels: small

#481 Adding explanation about arbitrary range of array types
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/02_Perspective.rst
Labels: small

#480 Editorial change: adding reference to section about generics.
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/02_Perspective.rst
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/07_Reusability.rst
Labels: small
