Repository AdaCore/learn, pull requests merged in 2020-11, with the labels that each got.

#440 Editorial changes: correcting some terminology.
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/06_Translation.rst
Labels: small

#437 GitHub actions
  .github/workflows/frontend-tests.js.yml
  .github/workflows/sphinx-tests.js.yml
  .travis.yml
  README.md
  travis_install.sh
  travis_script.sh
Labels: enhancement

#441 Adding section on interrupt handling
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/04_Embedded.rst
Labels: new section

#439 Adding section on volatile and atomic data
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/04_Embedded.rst
Labels: new section

#446 Editorial change: removing section on bare metal environment
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/04_Embedded.rst
Labels: small
