Repository AdaCore/learn, pull requests merged in 2020-10, with the labels that each got.

#394 Adding sections on configuration files
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/07_Reusability.rst
Labels: new section

#409 Adding section on object-oriented programming
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/02_Perspective.rst
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/07_Reusability.rst
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/Appendix_A_OOP.rst
  content/courses/Ada_For_The_C_Embedded_Developer/index.rst
Labels: new section

#404 Adding sections on records with discriminants and variant records
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/06_Translation.rst
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/07_Reusability.rst
Labels: new section

#423 Adding section: "Design by components using dynamic libraries"
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/07_Reusability.rst
Labels: new section

#425 Support for switch specification from rst.
  backend/app/widget/file.py
  backend/app/widget/project.py
  backend/app/widget/tasks.py
  backend/app/widget/widget_routes.py
  frontend/sphinx/widget_extension.py
  frontend/src/ts/comms.ts
  frontend/src/ts/types.ts
  frontend/src/ts/widget.ts
  frontend/tests/ts/comms.spec.ts
  frontend/tests/ts/widget.spec.ts
Labels: enhancement

#431 Typo in 02_Flow_Analysis.rst
  content/courses/intro-to-spark/chapters/02_Flow_Analysis.rst
Labels: typo

#429 Adding section on switches and optimizations
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/08_Performance.rst
Labels: new section

#433 Adding section about pointers and data copies
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/06_Translation.rst
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/08_Performance.rst
Labels: new section

#435 Adding section on overlays vs. unchecked conversions
  content/courses/Ada_For_The_C_Embedded_Developer/chapters/06_Translation.rst
Labels: new section
