Repository AdaCore/learn, pull requests merged in 2022-09, with the labels that each got.

#779 Adding section on limited types as parameters
  content/courses/advanced-ada/chapters/limited_types.rst
Labels: new section

#780 Multiple editorial changes in chapter on limited types
  content/courses/advanced-ada/chapters/aggregates.rst
  content/courses/advanced-ada/chapters/limited_types.rst
Labels: editorial

#781 Adding section on initialization and function return
  content/courses/advanced-ada/chapters/limited_types.rst
  content/courses/advanced-ada/chapters/statements.rst
Labels: new section, editorial

#776 Edit `Tasking` section of "Introducion to Ada"
  content/courses/intro-to-ada/chapters/tasking.rst
Labels: enhancement

#783 Frontend: major updates to Python and Node packages
  frontend/package.json
  frontend/requirements.txt
  frontend/requirements_frozen.txt
  frontend/sphinx/widget/templates/widget.html
  frontend/src/ts/editor.ts
  frontend/src/ts/server.ts
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
  frontend/yarn.lock
Labels: website infrastructure

#757 Adding section on anonymous access types
  content/courses/advanced-ada/chapters/access_types.rst
  content/courses/advanced-ada/chapters/types.rst
Labels: new section
