Repository AdaCore/learn, pull requests merged in 2022-08, with the labels that each got.

#764 Editorial changes to "Introduction to Embedded Systems Programming" course
  content/courses/intro-to-embedded-sys-prog/chapters/general_purpose_code_generators.rst
  content/courses/intro-to-embedded-sys-prog/chapters/handling_interrupts.rst
  content/courses/intro-to-embedded-sys-prog/chapters/interacting_with_devices.rst
  content/courses/intro-to-embedded-sys-prog/chapters/low_level_programming.rst
  content/courses/intro-to-embedded-sys-prog/chapters/multi_language_development.rst
Labels: editorial

#765 Add apt-get update before apt-get install to github action
  .github/workflows/sphinx-content-tests.js.yml
Labels: dependencies

#763 Fix some code blocks
  content/courses/Ada_For_The_Embedded_C_Developer/chapters/02_Perspective.rst
  content/courses/Ada_For_The_Embedded_C_Developer/chapters/05_SPARK.rst
  content/courses/Ada_For_The_Embedded_C_Developer/chapters/08_Performance.rst
  content/courses/intro-to-spark/chapters/01_Overview.rst
  content/courses/intro-to-spark/chapters/04_State_Abstraction.rst
  content/courses/intro-to-spark/chapters/05_Proof_Of_Functional_Correctness.rst
Labels: bug

#749 Draft changes to use AWS lambda function for the backend
  README.md
  Vagrantfile
  backend/.flaskenv
  backend/.gitignore
  backend/REQUIREMENTS.txt
  backend/app/__init__.py
  backend/app/widget/__init__.py
  backend/app/widget/container.py
  backend/app/widget/file.py
  backend/app/widget/lab.py
  backend/app/widget/project.py
  backend/app/widget/reporter.py
  backend/app/widget/tasks.py
  backend/app/widget/widget_routes.py
  backend/celery_worker.py
  backend/config/__init__.py
  backend/config/settings.py
  backend/dev.py
  backend/dev_server.sh
  backend/infrastructure/Dockerfile
  backend/infrastructure/preloader.c
  backend/tests/__init__.py
  backend/tests/conftest.py
  backend/tests/functional/__init__.py
  backend/tests/functional/run_program/test_run_singlefile_ada/results.json
  backend/tests/functional/run_program/test_run_singlefile_ada/test.adb
  backend/tests/functional/run_program/test_run_singlefile_error_ada/results.json
  backend/tests/functional/run_program/test_run_singlefile_error_ada/test.adb
  backend/tests/functional/widget_test.py
  backend/tests/pytest.ini
  backend/tests/unit/__init__.py
  backend/wsgi.py
  docs/LEARN Infrastructure.pdf
  docs/architecture.md
  frontend/Makefile
  frontend/package.json
  frontend/requirements.txt
  frontend/sphinx/widget_extension.py
  frontend/src/ts/comms.ts
  frontend/src/ts/download.ts
  frontend/src/ts/server-types.ts
  frontend/src/ts/server.ts
  frontend/src/ts/strings.ts
  frontend/src/ts/widget.ts
  frontend/tests/code_block.py
  frontend/tests/execute_rst_code_blocks.py
  frontend/tests/ts/comms.spec.ts
  frontend/tests/ts/download.spec.ts
  frontend/tests/ts/server.spec.ts
  frontend/tests/ts/widget.spec.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: website infrastructure

#770 Fix race condition that cause lab results to not be displayed
  frontend/src/ts/widget.ts
Labels: bug

#771 Python: updating some packages
  backend/.gitignore
  frontend/requirements.txt
  frontend/requirements_frozen.txt
Labels: website infrastructure

#773 Removing support for MOBI format
  .github/workflows/sphinx-books-tests.js.yml
  Vagrantfile
  content/courses/Ada_For_The_CPP_Java_Developer/index.rst
  content/courses/Ada_For_The_Embedded_C_Developer/index.rst
  content/courses/GNAT_Toolchain_Intro/index.rst
  content/courses/SPARK_for_the_MISRA_C_Developer/index.rst
  content/courses/advanced-ada/index.rst
  content/courses/advanced-spark/index.rst
  content/courses/intro-to-ada/index.rst
  content/courses/intro-to-embedded-sys-prog/index.rst
  content/courses/intro-to-spark/index.rst
  content/courses/whats-new-in-ada-2022/index.rst
  content/index.rst
  content/labs/bug-free-coding/index.rst
  content/labs/intro-to-ada/index.rst
  frontend/Makefile
Labels: website infrastructure

#777 Prevent user from spamming execute buttons
  frontend/src/ts/widget.ts
Labels: website infrastructure

#778 Placeholder for section: Parameter Modes and Associations
  content/courses/advanced-ada/chapters/subprograms.rst
Labels: editorial

#759 Adding section on Accessibility Levels and Rules
  content/courses/advanced-ada/chapters/access_types.rst
  content/courses/advanced-ada/chapters/exceptions.rst
Labels: new section

#772 Adding section on assignment and equality operators for limited types
  content/courses/advanced-ada/chapters/limited_types.rst
  content/courses/intro-to-ada/chapters/privacy.rst
Labels: new section

#774 Adding admonition on private scalar types
  content/courses/advanced-ada/chapters/types.rst
Labels: enhancement
