Repository AdaCore/learn, pull requests merged in 2023-10, with the labels that each got.

#938 Infrastructure updates
  .github/workflows/sphinx-books-tests.js.yml
  .github/workflows/sphinx-content-tests.js.yml
  .github/workflows/sphinx-plugin-tests.js.yml
  .github/workflows/typescript-tests.js.yml
  frontend/package.json
  frontend/requirements.txt
  frontend/requirements_frozen.txt
  frontend/yarn.lock
Labels: website infrastructure

#939 Sphinx: minor improvements to RTD theme integration
  frontend/sphinx/_templates/breadcrumbs.html
  frontend/sphinx/_templates/footer.html
  frontend/sphinx/conf.py
Labels: website infrastructure

#924 Adding section on accessibility rules and access-to-subprograms
  content/courses/advanced-ada/parts/resource_management/access_types.rst
Labels: new section

#928 Adding section on anonymous access-to-subprograms and related topics
  content/courses/advanced-ada/parts/resource_management/access_types.rst
  content/courses/advanced-ada/parts/resource_management/anonymous_access_types.rst
Labels: new section

#941 Introducing basic structure of upcoming course on Ada idioms
  content/courses/ada-idioms/chapters/appendices.rst
  content/courses/ada-idioms/chapters/introduction.rst
  content/courses/ada-idioms/conf.ini
  content/courses/ada-idioms/index.rst
  content/index.rst
  frontend/Makefile
Labels: website infrastructure

#943 Editorial change: replacing by correct word
  content/courses/Ada_For_The_Embedded_C_Developer/chapters/02_Perspective.rst
Labels: typo, editorial

#944 Frontend: updating some packages
  frontend/package.json
  frontend/requirements.txt
  frontend/requirements_frozen.txt
  frontend/yarn.lock
Labels: website infrastructure

#947 SCSS: adding scrollbar to side navigation (TOC)
  frontend/src/styles/learn.scss
Labels: website infrastructure

#948 SCSS: adding support for dark mode
  content/courses/intro-to-embedded-sys-prog/chapters/handling_interrupts.rst
  content/courses/intro-to-embedded-sys-prog/chapters/low_level_programming.rst
  content/courses/intro-to-embedded-sys-prog/chapters/multi_language_development.rst
  content/courses/intro-to-spark/chapters/01_Overview.rst
  content/courses/intro-to-spark/chapters/05_Proof_Of_Functional_Correctness.rst
  content/labs/bug-free-coding/chapters/stack.rst
  frontend/requirements.txt
  frontend/requirements_frozen.txt
  frontend/src/index.ts
  frontend/src/styles/_variables-dark.scss
  frontend/src/styles/_variables.scss
  frontend/src/styles/learn-dark.scss
  frontend/src/styles/learn.scss
Labels: website infrastructure

#949 Frontend: upgrading some packages
  frontend/package.json
  frontend/requirements.txt
  frontend/requirements_frozen.txt
  frontend/yarn.lock
Labels: website infrastructure

#950 Editorial change: hiding upcoming Ada Idioms course
  content/hidden.txt
Labels: website infrastructure

#952 Fix backend error being shown by mistake, which was hiding actual result
  frontend/package.json
  frontend/src/ts/widget.ts
Labels: bug, enhancement, javascript
